### ISSUE TITLE
not compile on Qt version 5.12.8

### ISSUE THREAD

**Issue by beho1der** [CURTLab/LVGLBuilder#10]
I Build on:
$ qmake -version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

**And get error:**

LVGLProperty.cpp: In member function ‘virtual void LVGLPropertyValT<T>::set(LVGLObject*, T)’:
LVGLProperty.cpp:289:12: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDebug’ and ‘const char [7]’)
  289 |   qDebug() << "Error:" << e.what();
      |            ^~ ~~~~~~~~
      |               |
      |               const char [7]
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from LVGLProperty.h:4,
                 from LVGLProperty.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:885:22: note: candidate: ‘QDebug operator<<(QDebug, const QVariant&)’
  885 | Q_CORE_EXPORT QDebug operator<<(QDebug, const QVariant &);
      |                      ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QJsonValue:1,
                 from LVGLProperty.h:5,
                 from LVGLProperty.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qjsonvalue.h:251:22: note: candidate: ‘QDebug operator<<(QDebug, const QJsonValue&)’
  251 | Q_CORE_EXPORT QDebug operator<<(QDebug, const QJsonValue &);
      |                      ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from LVGLImageData.h:4,
                 from LVGLCore.h:6,
                 from LVGLProperty.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h:57:21: note: candidate: ‘QDebug operator<<(QDebug, const QColor&)’
   57 | Q_GUI_EXPORT QDebug operator<<(QDebug, const QColor &);
      |                     ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from LVGLImageData.h:4,
                 from LVGLCore.h:6,
                 from LVGLProperty.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:189:21: note: candidate: ‘QDebug operator<<(QDebug, const QMatrix&)’
  189 | Q_GUI_EXPORT QDebug operator<<(QDebug, const QMatrix &);
      |                     ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from LVGLImageData.h:4,
                 from LVGLCore.h:6,
                 from LVGLProperty.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h:378:21: note: candidate: ‘QDebug operator<<(QDebug, const QTransform&)’
  378 | Q_GUI_EXPORT QDebug operator<<(QDebug, const QTransform &);
      |                     ^~~~~~~~
LVGLProperty.cpp: In instantiation of ‘void LVGLPropertyValT<T>::set(LVGLObject*, T) [with T = short unsigned int]’:
LVGLProperty.h:158:15:   required from here
LVGLProperty.cpp:288:4: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
  288 |  } catch (std::exception e) {
      |    ^~~~~
LVGLProperty.cpp: In instantiation of ‘void LVGLPropertyValT<T>::set(LVGLObject*, T) [with T = short int]’:
LVGLProperty.h:158:15:   required from here
LVGLProperty.cpp:288:4: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
make: *** [Makefile:9427: build/obj/LVGLProperty.o] Ошибка 1
