### ISSUE TITLE
Ubuntu, Build failed.

### ISSUE THREAD

**Issue by colesnicov** [CURTLab/LVGLBuilder#2]
Hello. Good job.
I do:
> qmake
> make

and i see:

```
gcc -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DFT_CONFIG_OPTION_ERROR_STRINGS -DFT2_BUILD_LIBRARY -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Ilvgl -Ifreetype/include -Ifreetype/builds/unix -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -isystem /usr/include/libdrm -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/obj/ftsystem.o freetype/builds/unix/ftsystem.c
freetype/builds/unix/ftsystem.c:21:10: fatal error: ftconfig.h: File not found
 #include <ftconfig.h>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:5548: recipe for target 'build/obj/ftsystem.o' failed
make: *** [build/obj/ftsystem.o] Error 1
```
When i try: 

```
denis@pc1:~/opt/LVGLBuilder$ locate ftconfig.h
/usr/include/freetype2/freetype/config/ftconfig.h
```

Fail to compile :(

**Comment by CURTLab** [comment]
Thanks.

It seems that I have forgotten to upload the `ftconfig.h` file to the unix build directory for freetype. Since I have no linux VM at the moment could you try to rebuild with the current fix?

**Comment by colesnicov** [comment]
:). I'll try it again, but latter..

**Comment by CURTLab** [comment]
I have tested the build on Ubuntu 18.04.4 with Qt 5.14.2 and it works fine for me

**Comment by colesnicov** [comment]
It's ok now.
